# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d0069a25a73715e2d840a71ee8e6b33c603b8633b060c42fb5b214e954f9a19bb734f6a92b924a534f23ab7b99cb51c1ce16b05d25385a5651291faff78013

test:
  secret_key_base: 280fb656c133facb23dc763c2f9b261c8016fa4f0b2499f3a55396bb03322bfcc6661b0a5292fb889514c9a0e97ef85aa8d419f722189bd9716cc0ac3cb086f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
